"""Lookup table mapping DuckDB schema names to guide file names.

Multiple schemas may map to the same guide. Schemas without a relevant guide
are absent from the mapping.
"""

# schema name -> guide file stem (without .md extension)
SCHEMA_TO_GUIDE: dict[str, str] = {
    "Accidents": "accidents_safety",
    "Airline": "airline_operations",
    "Basketball_women": "basketball_reporting",
    "Bupa": "medical_data_compliance",
    "CORA": "library_catalog",
    "Carcinogenesis": "toxicology_research",
    "Chess": "chess_idiosyncrasies",
    "CiteSeer": "library_catalog",
    "ConsumerExpenditures": "consumer_expenditures",
    "Countries": "world_geography",
    "CraftBeer": "craft_beer_inventory",
    "Credit": "credit_card_operations",
    "Dallas": "accidents_safety",
    "ErgastF1": "f1_racing_metrics",
    "Facebook": "social_media_analytics",
    "FNHK": "medical_data_compliance",
    "GOSales": "sales_reporting",
    "Hepatitis_std": "medical_data_compliance",
    "Hockey": "hockey_analytics",
    "KRK": "chess_idiosyncrasies",
    "Mondial": "world_geography",
    "NBA": "basketball_reporting",
    "NCAA": "basketball_reporting",
    "Pima": "medical_data_compliance",
    "SAP": "sales_reporting",
    "SAT": "satellite_telemetry",
    "SFScores": "restaurant_health_inspections",
    "SalesDB": "sales_reporting",
    "Seznam": "financial_operations",
    "Shakespeare": "library_catalog",
    "Student_loan": "financial_operations",
    "Toxicology": "toxicology_research",
    "UTube": "social_media_analytics",
    "UW_std": "university_academics",
    "Walmart": "weather_station_data",
    "ccs": "credit_card_operations",
    "classicmodels": "sales_reporting",
    "cs": "credit_card_operations",
    "employee": "employee_hr_policies",
    "financial": "financial_operations",
    "geneea": "election_polling",
    "imdb_MovieLens": "movie_ratings",
    "imdb_ijs": "movie_ratings",
    "lahman_2014": "baseball_sabermetrics",
    "medical": "medical_data_compliance",
    "mutagenesis": "toxicology_research",
    "nations": "world_geography",
    "northwind": "sales_reporting",
    "pubs": "library_catalog",
    "restbase": "restaurant_health_inspections",
    "sakila": "movie_ratings",
    "university": "university_academics",
    "voc": "shipping_logistics",
    "world": "world_geography",
}
